name: Cross Platform Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
 build:
    name: "Build shopping (${{ matrix.target.os }}, ${{ matrix.go-version }})"
    runs-on: ${{ matrix.target.host || 'ubuntu-latest' }}
    env:
      GO111MODULE: on
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
          - os: windows
            ext: .exe
          - os: freebsd
          - os: android
            args: -app-id shopping.sha${GITHUB_SHA}
          - os: darwin
            args: -app-id shopping.sha${GITHUB_SHA}
            host: macos-latest
          # web is currently not supported by shopping
          # - os: web

    steps:
      - name: Setup Go environment
        id: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/fyne-cross
          key: ${{ runner.os }}-build-cache-${{ hashFiles('go.sum') }}

      - name: Install Fyne and Fyne-cross
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          go install github.com/fyne-io/fyne-cross@latest
      - name: Install Podman
        if: ${{ runner.os == 'macos' }}
        run: |
          brew install podman
          podman machine init
          podman machine start
            
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build
        run: |
          fyne-cross \
            ${{ matrix.target.os }} \
            ${{ matrix.target.args }} \
            -debug \
            -name shopping${{ matrix.target.ext }}